name: Check SQL Server Data Platform Community
on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"
jobs:
  check-sql:
    runs-on: ubuntu-latest
    steps:
    - name: Run the action
      id: export
      uses: potatoqualitee/exodus@v1.1
      with:
        specific-twitter-accounts: DataGrillen, SQLBits, SQLServer, AzureSQL, databash_live, DataTgif, passdatasummit, sqlsaturday, groupbyconf, SQLServerRadio, sqlservercentrl, EightKbConf, KaySauter
        account-followers: DataGrillen, datasaturdays, databash_live, DataTgif, passdatasummit, sqlsaturday, groupbyconf, SQLServerRadio, EightKbConf
        accounts-following: DataGrillen, SQLBits, AzureSQL, SQLServer, redgate, databash_live, DataTgif, passdatasummit, sqlsaturday, groupbyconf, SQLServerRadio, sqlservercentrl, SQLServerMag, EightKbConf
        list-members: "1491474973998915587, 1569973251161616385"
        list-followers: "1569973251161616385"
        hashtags: "#sqlfamily"
        include-private: false
      env:
        BLUEBIRDPS_API_KEY: "${{ secrets.BLUEBIRDPS_API_KEY }}"
        BLUEBIRDPS_API_SECRET: "${{ secrets.BLUEBIRDPS_API_SECRET }}"
        BLUEBIRDPS_ACCESS_TOKEN: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN }}"
        BLUEBIRDPS_ACCESS_TOKEN_SECRET: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN_SECRET }}"
        BLUEBIRDPS_BEARER_TOKEN: "${{ secrets.BLUEBIRDPS_BEARER_TOKEN }}"