name: Check PowerShell Community
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  check-pwsh:
    runs-on: ubuntu-latest
    steps:
    - name: Run the action
      id: export
      uses: potatoqualitee/exodus@v1
      with:
        specific-twitter-accounts: PSConfEU, PSConfAsia, PowerShell_Team, PSHSummit, ATXPowershell, FrPSUG, PnwPowerShell, gnvpsug, rtpsug, NorwegianPUG, DenverCO_PSUG, NottsPSUG, ANZPSUG, hhpsug, JapanPSUG, IsraelPSUG, azPowershell, flpsug, SGPoShUG, chpsug, PSUGHannover, DuPSUG
        account-followers: PSConfEU, PSConfAsia, PSHSummit, PSSouthampton, ATXPowershell, FrPSUG, PnwPowerShell, gnvpsug, rtpsug, NorwegianPUG, DenverCO_PSUG, NottsPSUG, ANZPSUG, hhpsug, JapanPSUG, IsraelPSUG, azPowershell, flpsug, SGPoShUG, chpsug, PSUGHannover, DuPSUG
        accounts-following: PSConfEU, PSConfAsia, PowerShell_Team, PSHSummit, PSSouthampton, ATXPowershell, FrPSUG, PnwPowerShell, gnvpsug, rtpsug, NorwegianPUG, DenverCO_PSUG, NottsPSUG, ANZPSUG, hhpsug, JapanPSUG, IsraelPSUG, azPowershell, flpsug, SGPoShUG, chpsug, PSUGHannover, DuPSUG
        list-members: "749356646665629696, 1539374312662106113, 1265394461326094337"
        list-followers: "749356646665629696, 1265394461326094337"
        hashtags: "#powershell, #pwsh"
        include-private: false
      env:
        BLUEBIRDPS_API_KEY: "${{ secrets.BLUEBIRDPS_API_KEY }}"
        BLUEBIRDPS_API_SECRET: "${{ secrets.BLUEBIRDPS_API_SECRET }}"
        BLUEBIRDPS_ACCESS_TOKEN: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN }}"
        BLUEBIRDPS_ACCESS_TOKEN_SECRET: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN_SECRET }}"
        BLUEBIRDPS_BEARER_TOKEN: "${{ secrets.BLUEBIRDPS_BEARER_TOKEN }}"