name: Check PowerBI Community
on:
  workflow_dispatch:
jobs:
  check-sql:
    runs-on: ubuntu-latest
    steps:
    - name: Run the action
      id: export
      uses: potatoqualitee/exodus@v1
      with:
        specific-twitter-accounts: MSPowerBI, PowerBISummit, GuyInACube, Azure_Synapse, PowerBITips
        account-followers: PowerBISummit
        accounts-following: PowerBISummit, GuyInACube, Azure_Synapse, PowerBITips
        list-members: "1569622310122029056, 1517855020254994432"
        list-followers: "1569622310122029056, 1517855020254994432"
        hashtags: "#pbifamily"
        include-private: false
      env:
        BLUEBIRDPS_API_KEY: "${{ secrets.BLUEBIRDPS_API_KEY }}"
        BLUEBIRDPS_API_SECRET: "${{ secrets.BLUEBIRDPS_API_SECRET }}"
        BLUEBIRDPS_ACCESS_TOKEN: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN }}"
        BLUEBIRDPS_ACCESS_TOKEN_SECRET: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN_SECRET }}"
        BLUEBIRDPS_BEARER_TOKEN: "${{ secrets.BLUEBIRDPS_BEARER_TOKEN }}"